#!/usr/bin/env bash

set -e

USER=${USER}
SECRET_KEY_NAME=${SECRET_KEY_NAME}
# USER="platform-enablement"

if [ -z ${USER} ]; then
  echo "Please provide the artifactory user"
  exit 1
fi

if [ -z ${SECRET_KEY_NAME} ]; then
  echo "Please provide the secret key name"
  exit 1
fi


APIKEY=$(aws s3 cp --sse aws:kms s3://myob-jfrog-api-keys/$USER/APIKEY -)
AUTH=$(echo -n "$USER:$APIKEY" | base64)

cat > /tmp/config.json <<EOF
{
	"auths": {
		"imyob-docker-private.jfrog.io": {
			"auth": "$AUTH"
		}
	}
}
EOF
ARTIFACTORY_SECRET=$(cat /tmp/config.json | base64)

cat > /tmp/artifactory-docker-secret.yaml <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_KEY_NAME}
data:
  .dockerconfigjson: $ARTIFACTORY_SECRET
type: kubernetes.io/dockerconfigjson
EOF

kubectl apply -f /tmp/artifactory-docker-secret.yaml

rm -f /tmp/config.json /tmp/artifactory-docker-secret.yaml
