#!/usr/bin/env bash

set -e

USER=${USER}
SECRET_KEY_NAME=${SECRET_KEY_NAME}

if [ -z ${USER} ]; then
  echo "Please provide the artifactory user"
  exit 1
fi

if [ -z ${SECRET_KEY_NAME} ]; then
  echo "Please provide the secret key name"
  exit 1
fi

DOCKER_SERVER="imyob-docker-private.jfrog.io"
APIKEY=$(aws s3 cp --sse aws:kms s3://myob-jfrog-api-keys/$USER/APIKEY -)
DOCKER_EMAIL="platform-enablement@myob.com"

kubectl create secret docker-registry ${SECRET_KEY_NAME} --docker-server=${DOCKER_SERVER} --docker-username=${USER} --docker-password=${APIKEY} --docker-email=${DOCKER_EMAIL}
